[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "matplotlib>=3.10.3",
    "pillow>=11.3.0",
    "requests>=2.32.4",
]
